name: Deploy Database Migrations
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ariga/setup-atlas@v0
      - name: Deploy Atlas Migrations
        uses: ariga/atlas-action/migrate/apply@v1
        with:
          url: postgres://tuancao:bAbcam-fiksar-fazpa2@atlas-db.postgres.database.azure.com:5432/demo?search_path=public
          dir: migrations/