name: Deploy Database Migrations
on:
  push:
    branches:
      - master
jobs:
  # lint:
  #   services:
  #     # Spin up a postgres:15 container to be used as the dev-database for analysis.
  #     postgres:
  #       image: postgres:15
  #       env:
  #         POSTGRES_DB: dev
  #         POSTGRES_PASSWORD: pass
  #       ports:
  #         - 5432:5432
  #       options: >-
  #         --health-cmd pg_isready
  #         --health-interval 10s
  #         --health-start-period 10s
  #         --health-timeout 5s
  #         --health-retries 5
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: ariga/setup-atlas@v0
  #       with:
  #         cloud-token: ${{ secrets.ATLAS_CLOUD_TOKEN }}
  #     - uses: ariga/atlas-action/migrate/lint@v1
  #       with:
  #         dir: 'file://migrations'
  #         dev-url: postgres://postgres:pass@localhost:5432/dev?sslmode=disable
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ariga/setup-atlas@v0
      - name: Deploy Atlas Migrations
        uses: ariga/atlas-action/migrate/apply@v1.0.9
        with:
          url: ${{ secrets.DATABASE_URL }}
          dir: 'migrations/'